version: "3"
services:
    mysql:
        image: mysql:5
        container_name: mysql_docker
        labels:
            - "maintainer=xinliugm@gmail.com"
        ports:
            - 3306:3306
        environment:
            - TZ=Asia/Shanghai
            - MYSQL_ROOT_PASSWORD=mysqlpwd
        volumes:
#            - /etc/localtime:/etc/localtime:ro
            - ./var/lib/mysql:/var/lib/mysql

